# Generated by Django 3.2.5 on 2021-07-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя экстрасенса')),
                ('guess', models.IntegerField(default=0, verbose_name='Догадка')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень доверенности')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Догадка',
                'verbose_name_plural': 'Догадки',
                'db_table': 'medium',
            },
        ),
    ]
