# Generated by Django 3.2.5 on 2021-07-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя экстрасенса')),
                ('guess1', models.IntegerField(default=0, verbose_name='Догадка1')),
                ('guess2', models.IntegerField(default=0, verbose_name='Догадка2')),
            ],
            options={
                'verbose_name': 'Догадка',
                'verbose_name_plural': 'Догадки',
                'db_table': 'medium',
            },
        ),
    ]
