# Generated by Django 3.2.5 on 2021-07-12 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='level',
            field=models.IntegerField(default=0, verbose_name='Уровень доверенности'),
        ),
    ]
