# Generated by Django 3.2.5 on 2021-07-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0002_medium_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Пользовательское значение')),
            ],
            options={
                'verbose_name': 'История',
                'db_table': 'history',
            },
        ),
    ]
