# Generated by Django 3.2.5 on 2021-07-12 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('guess', '0003_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
